version: 2
jobs:
  testServerApp:
    docker:
      - image: circleci/node:10
    working_directory: ~/workspace
    steps:
      - checkout
      - run:
          name: cd
          command: cd ./serverApp
      - run:
          name: install
          command: npm install
      - run:
          name: test
          command: make test
workflows:
  version: 2
  testAll:
    jobs:
      - testServerApp
