version: 2
jobs:
  testServerApp:
    docker:
      - image: circleci/node:10
    working_directory: ~/junit
    steps:
      - checkout
      - run:
          name: install
          command: cd serverApp; npm install
      - run:
          name: test
          command: cd serverApp; make test
          environment:
            MOCHA_FILE: junit/serverApp/test-results.xml
          when: always
      - store_test_results:
          path: ~/junit
  testAndroidApp:
    docker:
      - image: circleci/android:api-28-alpha
    working_directory: ~/code
    steps:
      - checkout
      - run:
          name: install
          command: cd androidApp && make installDependencies
      - run:
          name: test
          command: cd androidApp && make unitTest
      - store_test_results:
          path: androidApp/app/build/test-results
workflows:
  version: 2
  testAll:
    jobs:
      - testServerApp
      - testAndroidApp
